version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - node_express
  node_express:
    image: node:10.14.1-alpine
    container_name: node_express
    hostname: node_express
    volumes:
      - "./server:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    ports:
      - "3000:3000"
    links:
      - mysql
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    hostname: mysql
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=lancul"